services:
  - type: web
    name: appzeto-food-frontend
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

